name: Build and Push to ACR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Azure CLI
      - name: Set up Azure CLI
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Step 3: Log in to ACR using workload identity
      - name: Log in to Azure Container Registry
        run: az acr login --name acrsbsharedservices

      # Step 4: Compute short commit hash
      - name: Compute short commit hash
        id: vars
        run: echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      # Step 5: Build and push the Docker image
      - name: Build and push Docker image
        run: |
          docker build -t acrsbsharedservices/${{ env.IMAGE_NAME }}:${{ env.COMMIT_HASH }} -f ${{ env.FILE }} ${{ env.CONTEXT }}
          docker push acrsbsharedservices/${{ env.IMAGE_NAME }}:${{ env.COMMIT_HASH }}
        env:
          CONTEXT: .
          FILE: ./Dockerfile
          IMAGE_NAME: my-image-name # Replace this with the desired image name
          COMMIT_HASH: ${{ env.COMMIT_HASH }} 
