name: CI workflow

on: 
  push:
    branches:
      - main
      - preprod
      - develop
env:
  buildConfiguration: Release
jobs:
  Build:
    name: 'Build job'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: dotnet build webapp
      run: dotnet build WebApplication1/WebApplication1.Service/WebApplication1.Service.csproj --configuration ${{ env.buildConfiguration }};
